# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'MindValleyTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MindValleyTest

pod 'AFNetworking', '~>2.6.3'

end

  target 'MindValleyTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MindValleyTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end


